CREATE TABLE IF NOT EXISTS projects(
  id integer primary key generated by default as identity,
  name text not null check (name <> ''),
  priority integer not null,
  description text,
  deliverydate date not null
);

CREATE TABLE IF NOT EXISTS tasks(
  id integer primary key generated by default as identity,
  name text not null check(name <> ''),
  done boolean not null,
  projectid integer REFERENCES projects(id),
  FOREIGN KEY (projectid) REFERENCES projects(id)
);

insert into projects(name, priority, description, deliverydate) values('Project 1', 1, 'Description 1', '2020-01-01');

-- insert another project, todo: make an app
INSERT INTO projects(name, priority, description, deliverydate) values('Project 2', 2, 'Description 2', '2020-01-02');

insert into tasks (name, done, projectid) values('Task 1', false, 1);
insert into tasks (name, done, projectid) values('download vuejs', true, 1);
insert into tasks (name, done, projectid) values('install vuejs', false, 2);
insert into tasks (name, done, projectid) values('download flutter', false, 2);